Repository ishubhamsharma00/customerUIPawpi, pull requests merged in 2024-01, with the labels that each got.

#20 Pawpi 22 fix signup page UI
  src/Components/Login and Signup/Signup.jsx
Labels: enhancement

#22 Update Readme File
  README.md
Labels: frontend

#34 Routes Document
  src/Documentation/routes.md
Labels: documentation

#24 (WIP Do not Merge ) Added Routing
  src/App.jsx
  src/Components/Accessories/Accessories.jsx
  src/Components/Cat/Cat.jsx
  src/Components/Clothes/Clothes.jsx
  src/Components/Collection/Collection.jsx
  src/Components/Collection/CollectionCardDetail.jsx
  src/Components/Collection/CollectionCategoryCarousel.jsx
  src/Components/Collection/CollectionCategoryDetails.jsx
  src/Components/Dog/BrandFilterSlider.jsx
  src/Components/Food/Food.jsx
  src/Components/ProductCard/ProductCard.jsx
  src/Components/Sort/sort.jsx
  src/Components/Start/Dog.jsx
  src/Components/index.jsx
  src/HOC/DefaultHOC.jsx
  src/context/index.js
  src/context/product/product-provider.js
  src/index.jsx
  src/layout/CheckoutLayout.jsx
  src/layout/DefaultLayout.jsx
  src/pages/Collection/Collection.jsx
  src/pages/DefaultBrands.jsx
  src/pages/DefaultBreed.jsx
  src/pages/DefaultCat.jsx
  src/pages/DefaultDog.jsx
  src/pages/DefaultHome.jsx
  src/pages/DefaultLifeStage.jsx
  src/pages/Temp.jsx
  src/pages/index.jsx
Labels: enhancement

#39 Dynamic url and data store in state
  src/Components/Collection/Collection.jsx
  src/Components/HeroProductPage/HeroProductPage.jsx
  src/Components/Navbar/NavLinks.jsx
  src/Components/Navbar/Navbar.jsx
  src/context/product/product-provider.js
  src/pages/Collection/Collection.jsx
Labels: enhancement
